MODEL:
  TYPE: hrnet
  NAME: hrnet_custom
  NUM_CLASSES: 100
  HRNET:
    STAGE1:
      NUM_MODULES: 1
      NUM_BRANCHES: 1
      NUM_BLOCKS: [2]
      NUM_CHANNELS: [64]
      BLOCK: 'BOTTLENECK'

    STAGE2:
      NUM_MODULES: 2
      NUM_BRANCHES: 2
      NUM_BLOCKS: [4, 4]
      NUM_CHANNELS: [64, 128]
      BLOCK: 'BASIC'
